/** Maps common search terms to keywords found in EMOJI_NAMES values */
export const EMOJI_SEARCH_ALIASES: Record<string, string[]> = {
  travel: [
    "airplane",
    "plane",
    "train",
    "car",
    "trip",
    "vacation",
    "hotel",
    "luggage",
    "passport",
    "cruise",
    "ship",
    "flight",
    "boat",
    "bus",
    "taxi",
    "metro",
    "subway",
    "camping",
    "beach",
    "mountain",
    "map",
    "compass",
    "ticket",
    "suitcase",
    "departing",
    "landing",
    "ferry",
    "rocket",
    "landmark",
  ],
  trip: ["travel", "vacation", "luggage", "passport", "flight", "hotel", "airplane", "train"],
  vacation: ["travel", "beach", "hotel", "luggage", "palm", "island", "sun", "trip"],
  flight: ["airplane", "plane", "airport", "departing", "landing", "travel"],
  train: ["railway", "metro", "subway", "locomotive", "bullet", "tram", "travel"],
  user: ["bust", "silhouette", "person", "profile", "account", "human"],
  users: ["busts", "silhouettes", "people", "group", "team", "crowd", "accounts"],
  people: ["person", "man", "woman", "human", "group", "family", "team", "users"],
  person: ["people", "human", "man", "woman", "adult", "user"],
  bust: ["silhouette", "user", "profile", "person", "account"],
  silhouette: ["bust", "user", "profile", "person"],
  group: ["people", "team", "users", "family", "crowd", "busts"],
  team: ["people", "group", "users", "office", "work"],
  family: ["people", "group", "parent", "child", "baby"],
  work: ["office", "business", "professional", "meeting", "computer", "briefcase"],
  office: ["work", "business", "professional", "computer", "briefcase", "document"],
  food: ["eat", "meal", "restaurant", "hungry", "cook", "kitchen", "lunch", "dinner"],
  animal: ["pet", "dog", "cat", "bird", "wild", "zoo"],
  money: ["dollar", "payment", "bank", "cash", "finance", "budget"],
  health: ["doctor", "medical", "hospital", "medicine", "nurse"],
  home: ["house", "building", "apartment", "room"],
  nature: ["tree", "plant", "flower", "forest", "mountain", "ocean"],
}

export function emojiMatchesSearch(
  emoji: string,
  emojiName: string,
  category: string,
  searchTerm: string,
): boolean {
  const tokens = searchTerm.toLowerCase().trim().split(/\s+/).filter(Boolean)
  if (tokens.length === 0) return true

  const haystack = `${emojiName} ${category}`.toLowerCase()

  return tokens.every((token) => {
    if (haystack.includes(token)) return true
    if (emoji.includes(token)) return true

    const aliases = EMOJI_SEARCH_ALIASES[token] || []
    return aliases.some((alias) => haystack.includes(alias))
  })
}

/** Additional emojis to merge into categories (names + category membership) */
export const EMOJI_EXTENSIONS = {
  names: {
    "👤": "bust in silhouette user person profile account avatar single",
    "👥": "busts in silhouette users people group team crowd accounts multiple",
    "👫": "woman and man holding hands couple people relationship",
    "👬": "men holding hands couple people relationship friends",
    "👭": "women holding hands couple people relationship friends",
    "🧑‍🤝‍🧑": "people holding hands couple friends relationship team",
    "🫂": "people hugging embrace friends support team",
    "👪": "family people group parents children home",
    "👨‍👩‍👧": "family man woman girl parents child people",
    "👨‍👩‍👧‍👦": "family man woman girl boy parents children people",
    "👨‍👩‍👦": "family man woman boy parents child people",
    "👨‍👩‍👦‍👦": "family man woman two boys parents children",
    "👨‍👩‍👧‍👧": "family man woman two girls parents children",
    "💁": "person tipping hand information help sassy assistant",
    "💁‍♂️": "man tipping hand information help assistant",
    "💁‍♀️": "woman tipping hand information help assistant",
    "🙋": "person raising hand volunteer question answer me",
    "🙋‍♂️": "man raising hand volunteer question",
    "🙋‍♀️": "woman raising hand volunteer question",
    "🙇": "person bowing respect apology thank you",
    "🙇‍♂️": "man bowing respect apology",
    "🙇‍♀️": "woman bowing respect apology",
    "🙅": "person gesturing no stop prohibited reject",
    "🙅‍♂️": "man gesturing no stop reject",
    "🙅‍♀️": "woman gesturing no stop reject",
    "🙆": "person gesturing ok yes accept approve",
    "🙆‍♂️": "man gesturing ok yes accept",
    "🙆‍♀️": "woman gesturing ok yes accept",
    "🤷": "person shrugging dont know idk unsure whatever",
    "🤷‍♂️": "man shrugging dont know idk unsure",
    "🤷‍♀️": "woman shrugging dont know idk unsure",
    "🧍": "person standing idle wait",
    "🧍‍♂️": "man standing idle wait",
    "🧍‍♀️": "woman standing idle wait",
    "🚶": "person walking pedestrian stroll",
    "🚶‍♂️": "man walking pedestrian stroll",
    "🚶‍♀️": "woman walking pedestrian stroll",
    "🧎": "person kneeling pray respect",
    "🧎‍♂️": "man kneeling pray respect",
    "🧎‍♀️": "woman kneeling pray respect",
    "🧏": "deaf person sign language hearing",
    "🧏‍♂️": "deaf man sign language",
    "🧏‍♀️": "deaf woman sign language",
    "💇": "person getting haircut barber salon",
    "💇‍♂️": "man getting haircut barber",
    "💇‍♀️": "woman getting haircut salon",
    "🙎": "person pouting upset annoyed",
    "🙍": "person frowning sad disappointed",
    "🧑‍🦯": "person with white cane blind accessibility",
    "🧑‍🦽": "person in manual wheelchair accessibility",
    "🧑‍🦼": "person in motorized wheelchair accessibility",
    "🚂": "locomotive steam train railway travel",
    "🚃": "railway car train carriage travel",
    "🚄": "high speed train bullet railway travel",
    "🚅": "bullet train fast railway travel japan",
    "🚆": "train railway metro travel commute",
    "🚇": "metro subway underground train travel city",
    "🚊": "tram trolley streetcar travel city",
    "🚉": "station train railway travel stop",
    "🚝": "monorail train travel",
    "🚞": "mountain railway train travel scenic",
    "🚟": "suspension railway train travel",
    "🚠": "mountain cableway gondola ski travel",
    "🚡": "aerial tramway cable car travel mountain",
    "🛶": "canoe boat kayak paddle travel water",
    "⛴️": "ferry boat ship travel water crossing",
    "🛳️": "passenger ship cruise ocean travel vacation",
    "🛸": "flying saucer ufo alien space travel",
    "🚀": "rocket space launch travel explore",
    "🧳": "luggage suitcase baggage travel trip vacation packing",
    "🎫": "ticket admission event travel concert entry pass",
    "🛂": "passport control customs border travel immigration",
    "🛄": "baggage claim airport travel luggage arrival",
    "🛅": "left luggage storage travel locker baggage",
    "🛎️": "bellhop bell hotel service travel accommodation",
    "⛺": "tent camping outdoors travel adventure",
    "🌁": "foggy bridge city travel mist",
    "🌃": "night with stars city travel evening",
    "🌄": "sunrise over mountains travel morning scenic",
    "🌅": "sunrise ocean travel morning scenic vacation",
    "🌉": "bridge at night city travel landmark",
    "🌌": "milky way stars night sky travel space",
    "🏕️": "camping tent outdoors travel adventure nature",
    "🏖️": "beach umbrella vacation travel summer sand",
    "🎡": "ferris wheel amusement park travel fun",
    "🎢": "roller coaster amusement park travel thrill",
    "🎠": "carousel horse amusement park travel fun",
    "🏰": "castle europe travel landmark historic",
    "🏯": "japanese castle travel landmark historic",
    "🗼": "tokyo tower landmark travel japan",
    "🗽": "statue of liberty landmark travel new york usa",
    "🗺️": "world map travel geography explore planning",
    "🧭": "compass navigation direction travel explore orient",
  } as Record<string, string>,
  people: [
    "👤",
    "👥",
    "👫",
    "👬",
    "👭",
    "🧑‍🤝‍🧑",
    "🫂",
    "👪",
    "👨‍👩‍👧",
    "👨‍👩‍👧‍👦",
    "👨‍👩‍👦",
    "👨‍👩‍👦‍👦",
    "👨‍👩‍👧‍👧",
    "💁",
    "💁‍♂️",
    "💁‍♀️",
    "🙋",
    "🙋‍♂️",
    "🙋‍♀️",
    "🙇",
    "🙇‍♂️",
    "🙇‍♀️",
    "🙅",
    "🙅‍♂️",
    "🙅‍♀️",
    "🙆",
    "🙆‍♂️",
    "🙆‍♀️",
    "🤷",
    "🤷‍♂️",
    "🤷‍♀️",
    "🧍",
    "🧍‍♂️",
    "🧍‍♀️",
    "🚶",
    "🚶‍♂️",
    "🚶‍♀️",
    "🧎",
    "🧎‍♂️",
    "🧎‍♀️",
    "🧏",
    "🧏‍♂️",
    "🧏‍♀️",
    "💇",
    "💇‍♂️",
    "💇‍♀️",
    "🙎",
    "🙍",
    "🧑‍🦯",
    "🧑‍🦽",
    "🧑‍🦼",
  ],
  travel: [
    "🚂",
    "🚃",
    "🚄",
    "🚅",
    "🚆",
    "🚇",
    "🚊",
    "🚉",
    "🚝",
    "🚞",
    "🚟",
    "🚠",
    "🚡",
    "🛶",
    "⛴️",
    "🛳️",
    "🛸",
    "🚀",
    "🧳",
    "🎫",
    "🛂",
    "🛄",
    "🛅",
    "🛎️",
    "⛺",
    "🌁",
    "🌃",
    "🌄",
    "🌅",
    "🌉",
    "🌌",
    "🏕️",
    "🏖️",
    "🎡",
    "🎢",
    "🎠",
    "🏰",
    "🏯",
    "🗼",
    "🗽",
    "🗺️",
    "🧭",
  ],
}
